 prog: main.cpp helper_functions.cpp solve_network.cpp solve_dde.cpp backprop.cpp numerical_gradient.cpp
	g++ -std=c++11 -o prog main.cpp helper_functions.cpp solve_network.cpp solve_dde.cpp backprop.cpp numerical_gradient.cpp -Ofast -llapack -lblas
