 prog: main.cpp helper_functions.cpp solve_network.cpp solve_dde.cpp backprop.cpp numerical_gradient.cpp global_constants.h
	g++ -std=c++11 -Ofast -o prog main.cpp helper_functions.cpp solve_network.cpp solve_dde.cpp backprop.cpp numerical_gradient.cpp -Ofast -llapack -lblas -larmadillo
